baseurl: "//ycpcs.github.io/cs100-fall2019"
markdown: kramdown
highlighter: rouge
coursename: "CS 100"

kramdown:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
